modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "${mod_license}"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_ver}" #mandatory
displayName = "${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/RealDarkStudios/rdslib/forge-1.20.X/versions.json" #optional
#displayURL="http://example.com/" #optional
#logoFile="rdslib.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "${mod_authors}" #optional
displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description = '''${mod_description}'''
[[dependencies.${mod_id}]] #optional
# the modid of the dependency
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"