modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "MIT"
#issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId = "rdslib" #mandatory
version = "1.20-0.2.0.3" #mandatory
displayName = "RDSLib" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
#logoFile="rdslib.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors = "RealDarkStudios" #optional
displayTest="MATCH_VERSION" # MATCH_VERSION is the default if nothing is specified (#optional)

description = '''
A library mod for RDS mods
'''
[[dependencies.rdslib]] #optional
# the modid of the dependency
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.rdslib]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.20.1)"
ordering = "NONE"
side = "BOTH"
